Fix defaults.

diff --git a/.forgejo/workflows/build.yaml b/.forgejo/workflows/build.yaml
--- a/.forgejo/workflows/build.yaml
+++ b/.forgejo/workflows/build.yaml
@@ -398,14 +398,14 @@ jobs:
           trap "rm -f $GNUSTEP_CONFIG_FILE" EXIT
 
           # We use the isolated 'PakManager' domain to avoid messing up the host's global defaults
-          if [ -x "$HERE/usr/System/Tools/defaults" ]; then
+          if [ -x "$HERE/usr/Local/Tools/defaults" ]; then
             echo "Running defaults command..."
-            "$HERE/usr/System/Tools/defaults" write PakManager GSTheme "Eau" || true
-            "$HERE/usr/System/Tools/defaults" write PakManager NSFont "Sans" || true
-            "$HERE/usr/System/Tools/defaults" write PakManager NSUserFont "Sans" || true
-            "$HERE/usr/System/Tools/defaults" write PakManager NSUserFixedPitchFont "Monospace" || true
+            "$HERE/usr/Local/Tools/defaults" write PakManager GSTheme "Eau" || true
+            "$HERE/usr/Local/Tools/defaults" write PakManager NSFont "Sans" || true
+            "$HERE/usr/Local/Tools/defaults" write PakManager NSUserFont "Sans" || true
+            "$HERE/usr/local/Tools/defaults" write PakManager NSUserFixedPitchFont "Monospace" || true
           else
-            echo "ERROR: defaults tool not found at $HERE/usr/System/Tools/defaults"
+            echo "ERROR: defaults tool not found at $HERE/usr/Local/Tools/defaults"
           fi
 
           REAL_BIN=$(find "$HERE" -type f -name "PakManager" -exec file {} \; 2>/dev/null | grep "ELF" | cut -d: -f1 | head -n 1 || true)
